# Railway.toml configuration for SkiPay
# Deploys two services: server (backend) and client (frontend)

[[services]]
name = "server"
dockerfile = "apps/server/Dockerfile"

[services.healthcheck]
path = "/healthz"
timeout = 10
interval = 30

[[services]]
name = "client"
dockerfile = "apps/client/Dockerfile"
